version: "3.7"

services:

  #  chkeeper:
  #    container_name: chkeeper
  #    image: clickhouse/clickhouse-keeper:22.12-alpine
  #    depends_on:
  #      - chnode1
  #    ports:
  #      - 9181:9181
  #    volumes:
  #      - type: volume
  #        source: chkeeper-logs
  #        target: /var/lib/clickhouse/coordination/log 
  #      - ./ch-keeper.xml:/etc/clickhouse-keeper/keeper_config.xml

  chnode1:
    container_name: chnode1
    hostname: chnode1
    image: clickhouse/clickhouse-server:22.12
    depends_on:
      - chnode2
      - chnode3
    ports:
      - 9300:9000
      - 8123:8123
      - 9181:9181
    volumes:
      - type: volume
        source: chnode1-data
        target: /var/lib/clickhouse
      - type: volume
        source: chnode1-logs
        target: /var/log/clickhouse-server
      - ./chnode1-config.xml:/etc/clickhouse-server/config.xml

  chnode2:
    container_name: chnode2
    hostname: chnode2
    image: clickhouse/clickhouse-server:22.12
    depends_on:
      - chnode3
    ports:
      - 9301:9000
      - 8124:8123
      - 9182:9181
    volumes:
      - type: volume
        source: chnode2-data
        target: /var/lib/clickhouse
      - type: volume
        source: chnode2-logs
        target: /var/log/clickhouse-server
      - ./chnode2-config.xml:/etc/clickhouse-server/config.xml

  chnode3:
    container_name: chnode3
    hostname: chnode3
    image: clickhouse/clickhouse-server:22.12
    ports:
      - 9302:9000
      - 8125:8123
      - 9183:9181
    volumes:
      - type: volume
        source: chnode3-data
        target: /var/lib/clickhouse
      - type: volume
        source: chnode3-logs
        target: /var/log/clickhouse-server
      - ./chnode3-config.xml:/etc/clickhouse-server/config.xml

volumes:
  #  chkeeper-logs:
  chnode1-data:
  chnode1-logs:
  chnode2-data:
  chnode2-logs:
  chnode3-data:
  chnode3-logs:
